# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:p2CkvDB1IugppBMW1gM6axgsSA==,iv:2poGceWPdxIoc54RA/uz/VEcuMBwCob/IDvivvk+5yw=,tag:rnRRzR8g3E/VkWOiG8Z9xA==,type:str]
    api-key: ENC[AES256_GCM,data:n+p8rJ83Qow3yi199J5zWDFxuImQEg3CSMEZxoGot0AkLuAO0g==,iv:KBIRTe1R4vgt/HBJaA9U0nEcauog8S62OCcCTdSfogo=,tag:+xASPvYeizqa/sVRmzPUBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7hhqxzl3xkmlhk0d25k2eapsv8sl80m995y7hatgcjm85v8zaqqme3qhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZUdkWGNwTnptNUlyVUZT
            WG9Mcnh2TzRmMzYvSmdMUDNXeHZJRys2NGhFClBMR3pYVDNsaDRFc3Jkb2l0L2hU
            cExGbFNMK0M1Z0dyNm5hV21yaWtxd0UKLS0tIEhDckk3MHoyMW5XSjlwY2RmemNx
            RXNuUFcyWUdLVzhJQVZocThlVFdzVkEKQNgA0x1heV1pVqagw+8V099yskq+k97E
            bZ8nSm7LeLnLxnbDmUnhhz8+NPu7vKx207V9X0qyO34Udaq3+sZn1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-25T18:53:03Z"
    mac: ENC[AES256_GCM,data:2KoHKgOxjnuzEfnUX/X+U9Eb2B85ubMAudE/MAXEjPcKK10EgnaF5SlgFwulmsVR9qC2MrKxflwxNuVmdPcHHT8oFcVMHC0S6yzZi+mkCnpz4B5oKWZuwzqpV63AHqBiNXUR7rCMLfh2wH2Ic6tDdIVPu3nqcdWeJmD1dGJZT1Y=,iv:fnqAd9AburAEIZbM2cJ2q5282r42rk//NiX09J2lh8E=,tag:37guIJyTqxlToQdJ14iWVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
