# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:O9YrPp2UjGZ/2FQadg==,iv:wHMW7bAyXYuyH5puR5qT8MwXMWm9mpvVoOJ0hyRyYP8=,tag:dr7jerYYZiKo7k7my3BKWw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fxpgCeriExc5Lrwq+LzoM7HjYA==,iv:0jYwH3jxsBHu2fxzAnWwUzOfRiYaWwnZrId0vYTXob0=,tag:NuzLepdEEsfpFGkp4J3TJw==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:WuvGSkD+c6K+D7kJEv4T,iv:CxxM9CqdXJII9fKZnlUBGzxBiKBVnWODlL01elOfZoY=,tag:ZEKz3LdlcbhPWT3Os5kQiA==,type:str]
    PRIVATE_DNS_PRIMARY: ENC[AES256_GCM,data:1iG5VQc8R1Wq5cv4,iv:zzRxRWuvX0BrA99e1HcTiGx7rdkcAn7OP/x/9bVjy0A=,tag:2/dhlObNEUCi0VrfDmwCrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7hhqxzl3xkmlhk0d25k2eapsv8sl80m995y7hatgcjm85v8zaqqme3qhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNFhWcjZmSStwMjVmQThS
            MlI2d09XSWFVQUxkeDBGdElNOFVVT1VnUTJJCndXQnU5ZTBET2pQYTJ1cHg1anZZ
            UURFQVgxQ0pnZktiRWlBSHl1ZS9UOTgKLS0tIHl1NXJIY1djUjAzWEp3bXZVZ2Fp
            ZU9PQ2xDVExYaitlZ2Z2YlR1aXIwVU0KwrcnvmGuuL1REdUWkbpnpWX43w66Csc1
            /HwOSXHf0VwZiwnpdyTaf6UUHuFspmUEuYlGF/XAXQI9Lqz+yZv4oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-30T20:06:06Z"
    mac: ENC[AES256_GCM,data:Zmv2X2L67lSwFMXHaUPER0PL1VSsui/SBEZv9SyrKO3W64iMoDG3opFp58xLSCU9MG5iewpXUSkcGHwZNv2/4eXVYXc3X3EVZ/1x82wor4Tow+kDEt8lMwpzurbVsUuBSZWvq+ZMDY964FkahMwxxHPAARN7aJvS3/4bLT6u7rg=,iv:EiCrlp4d/7PxfB7hJUYnjj3aZlyemIE48/hoqsDKD3k=,tag:+V+iU+6HCxMktpJpa1ir6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
