# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:O9YrPp2UjGZ/2FQadg==,iv:wHMW7bAyXYuyH5puR5qT8MwXMWm9mpvVoOJ0hyRyYP8=,tag:dr7jerYYZiKo7k7my3BKWw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fxpgCeriExc5Lrwq+LzoM7HjYA==,iv:0jYwH3jxsBHu2fxzAnWwUzOfRiYaWwnZrId0vYTXob0=,tag:NuzLepdEEsfpFGkp4J3TJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7hhqxzl3xkmlhk0d25k2eapsv8sl80m995y7hatgcjm85v8zaqqme3qhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNFhWcjZmSStwMjVmQThS
            MlI2d09XSWFVQUxkeDBGdElNOFVVT1VnUTJJCndXQnU5ZTBET2pQYTJ1cHg1anZZ
            UURFQVgxQ0pnZktiRWlBSHl1ZS9UOTgKLS0tIHl1NXJIY1djUjAzWEp3bXZVZ2Fp
            ZU9PQ2xDVExYaitlZ2Z2YlR1aXIwVU0KwrcnvmGuuL1REdUWkbpnpWX43w66Csc1
            /HwOSXHf0VwZiwnpdyTaf6UUHuFspmUEuYlGF/XAXQI9Lqz+yZv4oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-25T18:53:03Z"
    mac: ENC[AES256_GCM,data:CvW680GX07Z9Vd229hGeJGylaSjDfqSMKY4+55PZj372a/FFRoznF3Fz9m0h180RNGLGnLIS5FZJf/JSIraAlR1FH8zfl3LbTU8h3Q25xgP5GqjNuYF+qR2KkFZ+h+60R67Kt77lt4SPYD4USq4rkNqK7LYxI9sVsme30RjbrY4=,iv:NRWIay00NbOyXBUnYZRFzPpYh2v4i14F0DCsCunTLz8=,tag:Df5MTz3W2be+2LlNeKKyyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
