# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: internal-dns
    namespace: networking
    labels:
        app.kubernetes.io/name: internal-dns
        app.kubernetes.io/instance: internal-dns
data:
    rfc2136_tsig_secrect: ENC[AES256_GCM,data:CrLxFX/E56xmzWlqfKcEtRPg0LD17PHfMA8TJr5R05R4xn3217vwgcGg6Yk=,iv:1Vss0SmRWYjNpMlU7bzhd7fuLpDTv+UbqNTj8m/4YEs=,tag:MR5zoAJJXexJKAtOvTokMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j7hhqxzl3xkmlhk0d25k2eapsv8sl80m995y7hatgcjm85v8zaqqme3qhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZUdkWGNwTnptNUlyVUZT
            WG9Mcnh2TzRmMzYvSmdMUDNXeHZJRys2NGhFClBMR3pYVDNsaDRFc3Jkb2l0L2hU
            cExGbFNMK0M1Z0dyNm5hV21yaWtxd0UKLS0tIEhDckk3MHoyMW5XSjlwY2RmemNx
            RXNuUFcyWUdLVzhJQVZocThlVFdzVkEKQNgA0x1heV1pVqagw+8V099yskq+k97E
            bZ8nSm7LeLnLxnbDmUnhhz8+NPu7vKx207V9X0qyO34Udaq3+sZn1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-30T20:07:38Z"
    mac: ENC[AES256_GCM,data:dfXs5hO8e/9M+dMsX3adRcSqTICLDR1YeDbuAC256luguoc3zdslsueY9tWX2NnHHq4QZbKzUC90rOy/uXky1qigDwKExlnRdB2ON9QRl358IilrnenM21p0qay/KbBo2DZieh2dMTH83FySIAi208nqaE7XqSAoco7/dm03EYE=,iv:np95poOGib+XK4s+qGLG09mqnI9UJz/aupqA2UGsegg=,tag:7ZVcNdiaIAHpz/AKwfTCIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
